version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for the database...';
        sleep 5;
      done;
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      echo \"from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" | python manage.py shell &&
      daphne -b 0.0.0.0 -p 8000 kii.asgi:application"
    volumes:
      - .:/app
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=kii.settings
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
